language: node_js
node_js:
- 0.12.7
install:
- npm install -g gulp-cli bower coffee-script
- npm install
- bower install
script: gulp travis-test
addons:
  sauce_connect:
    username: hansottowirtz
  jwt:
    secure: Yhq9C3oglRUNR4JVR7YwZr/ONzqPuVuliM1HwZgUwpBibY6EwGAQ5GtvU/kJ8gHlkdYtpDgcTQp0XnQQA/zqD9y1C+tmuVInDVBPl21um5BY69b2DhSV7SRQxML4ElSyt+OVrGam2F/GIM6JqA20kQzfUOJhKjIe8sj+GcDbDX6l7LJs5zRpyV7DiCgdlZMwcxFfWmG0zDHbGMbRQz5np8xfDtmgTPrMlNlAe6dtqgF40U3b4xmk4ZqkHJ8GTTgJdiyqLh9N6tK/U4MIpMAtsk3bnPVwOzURnBmd3k+ZSwfOUOnVIqL+212zAKvzyt6ys4EVe+OZWEi+yyFc59icRjRAG/8TBuD5wYq/o+SsoHR6m9fnia/GnlBNQlA0vbjvRhXmQViwPJD9n6NTnH6vc9CRkhDTkK4+soUju+nyVMnW9f/paBNhj3IudHrwJH8E1XXMBAbWP56biQcWZ9vfGgaWcSc6ApsWK0XSNVQw/HIDIK0IN9dltseMUhRW1pJSfc3qNoCiGjdN7dWoIGBDSCTIUWLtidFB+0PBlSuKcNvka7+0EZaNyS0WKy/2OMY1nuPcToAJ1Z0zPb/uJjiVKFLmETfI3vmeBoPBoLpBNv/v+y1FuT+mQR89+2M82icWEy0b+uUK6fufh+l14ZKrEIGFekReIuP0joqq2UWKUwI=
